<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="user" name="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute" tests="27" failures="1" timestamp="5 Mar 2018 11:00:21 GMT" time="279.185" errors="4">
  <testcase name="ERT_SUMM_17_Validate_ERT_count" time="0.003" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_31_Verify_timeOf_Arrival_At_destination" time="0.769" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_03_Verify_the_ERT_summary_report_page" time="0.266" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_40_Verify_Action_taken_by_ERT_and_RCR_Column" time="0.183" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_01_Verify_HomePage" time="120.990" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_04_Verify_DateEntry_Manually" time="15.307" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_32_Verify_Total_responding_Time" time="0.109" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_37_38_Validate_the_ERT_Relieving_Time_column" time="0.127" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_41_42_Verify_Action_taken_by_ERT_and_RCR_Column" time="0.156" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_33_34_Verify_KM_coveredIn_ADT" time="0.031" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute">
    <error type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.Cogniphy.Protection.Muthoot.Reports.ERTSummay_Report.verifyKMCovered(ERTSummay_Report.java:128)
	at com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_33_34_Verify_KM_coveredIn_ADT(ReportsSiute.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- ERT_SUMM_33_34_Verify_KM_coveredIn_ADT -->
  <testcase name="ERT_SUMM_07_Verify_ClientFilter" time="0.163" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_18_Verify_ReportAt_TimeFormat" time="1.402" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_06_Verify_DateFiter_For_Morethan_90days" time="91.105" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_02_Verify_the_Reports_menu_on_top_bar" time="7.671" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_08_Verify_SessionFilter" time="3.733" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_19_Validate_the_ERT_Reported_AT_Column" time="0.413" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_39_Verify_the_Irregularities_column" time="0.132" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_20_Validate_ReportAt_with_GaurdCheckList_ReportTime" time="0.000" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_05_Verify_DateFiter_For_FutureDates" time="1.281" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_43_44_45_Validate_odometer_Values" time="0.360" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_35_Validate_Total_KM_run_by_ERT" time="0.497" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute">
    <error type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.Cogniphy.Protection.Muthoot.Reports.ERTSummay_Report.validateKMsRunByVehicles(ERTSummay_Report.java:299)
	at com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_35_Validate_Total_KM_run_by_ERT(ReportsSiute.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- ERT_SUMM_35_Validate_Total_KM_run_by_ERT -->
  <testcase name="ERT_SUMM_16_Verify_ERTColumn" time="28.939" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute">
    <error type="org.openqa.selenium.StaleElementReferenceException" message="stale element reference: element is not attached to the page document
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: &#039;3.8.1&#039;, revision: &#039;6e95a6684b&#039;, time: &#039;2017-12-01T18:33:54.468Z&#039;
System info: host: &#039;USER&#039;, ip: &#039;192.168.2.109&#039;, os.name: &#039;Windows 8.1&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.3&#039;, java.version: &#039;1.8.0_91&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.33.506120 (e3e53437346286..., userDataDir: C:\Users\121\AppData\Local\...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 64.0.3282.186, webStorageEnabled: true}
Session ID: 8dbba936c255816e9b354797745ed300">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'USER', ip: '192.168.2.109', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.33.506120 (e3e53437346286..., userDataDir: C:\Users\121\AppData\Local\...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 64.0.3282.186, webStorageEnabled: true}
Session ID: 8dbba936c255816e9b354797745ed300
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:160)
	at com.Cogniphy.Protection.Muthoot.Reports.ERTSummay_Report.namesFrom_Application(ERTSummay_Report.java:380)
	at com.Cogniphy.Protection.Muthoot.Reports.ERTSummay_Report.verifyAll_ERTs(ERTSummay_Report.java:388)
	at com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_16_Verify_ERTColumn(ReportsSiute.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- ERT_SUMM_16_Verify_ERTColumn -->
  <testcase name="ERT_SUMM_27_Validate_ADTRecived_Time" time="0.333" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_21_22_Validate_No_of_the_branches_visited_column" time="4.480" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
  <testcase name="ERT_SUMM_09_Verify_ReportTitle" time="0.113" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute">
    <failure type="java.lang.AssertionError" message="Does Not Match expected [ERT ACTION REPORT SUMMARY OF RCR MUTHOOT KOCHI - RCR REGION ON 18 DEC 2017 Morning ERT] but found [2018-03-05 Morning ERT]">
      <![CDATA[java.lang.AssertionError: Does Not Match expected [ERT ACTION REPORT SUMMARY OF RCR MUTHOOT KOCHI - RCR REGION ON 18 DEC 2017 Morning ERT] but found [2018-03-05 Morning ERT]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.Cogniphy.Protection.Muthoot.Reports.ERTSummay_Report.verifyReportTitle(ERTSummay_Report.java:44)
	at com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_09_Verify_ReportTitle(ReportsSiute.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ERT_SUMM_09_Verify_ReportTitle -->
  <testcase name="ERT_SUMM_46_Validate_total_Count" time="0.001" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute">
    <error type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_46_Validate_total_Count(ReportsSiute.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- ERT_SUMM_46_Validate_total_Count -->
  <testcase name="ERT_SUMM_10_Verify_TitleRow" time="0.621" classname="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
</testsuite> <!-- com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute -->
